"""
Shared QSS style constants and helpers for DICOM Sync GUI.

Application-wide dark theme lives here as ``DARK_THEME``; per-button
inline styles are generated by ``_button_style`` and exposed as
top-level constants so call sites read the same as before.
"""


def _button_style(bg: str, bg_hover: str,
                  padding: str = "6px 14px",
                  bold: bool = True) -> str:
    """Return a QSS snippet for a coloured QPushButton.

    *bg* — base background colour
    *bg_hover* — hover background colour
    *padding* — CSS padding shorthand
    *bold* — when True (default) sets ``font-weight: bold``
    """
    weight = "font-weight: bold; " if bold else ""
    return (
        f"QPushButton {{ background: {bg}; color: white; "
        f"padding: {padding}; border-radius: 4px; {weight}}}"
        f"QPushButton:hover {{ background: {bg_hover}; }}"
        f"QPushButton:disabled {{ background: #7f8c8d; }}"
    )


# ── Coloured action buttons ──────────────────────────────────────────────

BTN_GREEN = _button_style("#27ae60", "#2ecc71")
BTN_GREEN_LARGE = _button_style("#27ae60", "#2ecc71", padding="8px 22px")
BTN_RED = _button_style("#c0392b", "#e74c3c")
BTN_RED_LARGE = _button_style("#c0392b", "#e74c3c", padding="10px 24px")
BTN_BLUE = _button_style("#2980b9", "#3498db")
BTN_BLUE_LARGE = _button_style("#2980b9", "#3498db", padding="8px 18px")
BTN_START = _button_style("#27ae60", "#2ecc71", padding="10px 24px", bold=False)
BTN_STOP = _button_style("#c0392b", "#e74c3c", padding="10px 24px", bold=False)
BTN_OK_BLUE = _button_style("#2980b9", "#3498db", padding="8px 24px")
BTN_DOWNLOAD_SELECTED = _button_style(
    "#d35400", "#e67e22", padding="10px 24px", bold=False)
# Amber / orange — used for user-initiated cycle-restart actions
# (e.g. the dashboard Restart button: tears the engine down and
# brings a fresh one up).  Mid-impact: bigger than a plain blue
# action but not destructive like a red Stop / Remove.
BTN_AMBER = _button_style("#e67e22", "#f39c12")
BTN_AMBER_LARGE = _button_style(
    "#e67e22", "#f39c12", padding="8px 22px")

# Muted helper-text style for dialog hint labels.
LBL_HINT_STYLE = "QLabel { color: #969696; }"


# ── Accent palette ───────────────────────────────────────────────────────
# Foreground accents for status text and table cells.  Green / yellow /
# red live in gui.study_rate (single source of truth, shared with the
# studies-per-hour colour bands); these are the remaining accents, kept
# here so gui.dashboard and gui.queue_table can share them without one
# importing the other.
COLOR_ORANGE = "#f39c12"
COLOR_BLUE_ACCENT = "#3498db"
COLOR_MUTED = "#969696"
# Warning / error text (the completions outlier band, the resend
# warning in the examination lookup).
COLOR_DANGER = "#e74c3c"
# The theme's link/heading blue, used for section headings and
# "what am I editing" hints inside dialogs.
COLOR_LINK = "#2980b9"


# ── Shared surface colours ───────────────────────────────────────────────
# These mirror values baked into DARK_THEME below.  They live here as
# named constants because widgets that build an inline stylesheet (the
# dashboard's throughput readouts, its filter dropdown and its restart
# banner) used to hardcode the same hex strings, so a theme change had to
# be chased across several files to stay consistent.

SURFACE_BG = "#2c2c2c"
SURFACE_BORDER = "#555"
TEXT_DEFAULT = "#d4d4d4"
TEXT_ON_ACCENT = "#ffffff"

# Tinted backgrounds behind the colour-coded throughput readouts —
# a dark wash of the same hue as the foreground colour.
STAT_BG_GOOD = "#1a3a1a"
STAT_BG_BAD = "#3a1a1a"

# Amber banner for the "settings changed, restart the service" hint.
BANNER_WARN_BG = "#7f6000"


def stat_label_style(color: str, background: str) -> str:
    """QSS for one colour-coded throughput readout (images/minute)."""
    return (
        f"QLabel {{ color: {color}; background: {background}; "
        f"border: 1px solid {SURFACE_BORDER}; border-radius: 6px; "
        f"padding: 6px; }}"
    )


# Multi-select dropdown button in the dashboard's Institution Filter box.
TOOLBTN_FILTER = (
    f"QToolButton {{ padding: 5px 12px; "
    f"border: 1px solid {SURFACE_BORDER}; border-radius: 4px; "
    f"background: {SURFACE_BG}; min-width: 200px; text-align: left; }}"
    f"QToolButton::menu-indicator {{ subcontrol-position: right center; }}"
)

# "Settings changed — restart the service" banner.
LBL_RESTART_BANNER = (
    f"QLabel {{ background: {BANNER_WARN_BG}; color: {TEXT_ON_ACCENT}; "
    f"padding: 8px; border-radius: 4px; font-weight: bold; }}"
)


# ── Application-wide dark theme ──────────────────────────────────────────

DARK_THEME = """
    QMainWindow, QDialog, QWidget {
        background-color: #1e1e1e;
        color: #d4d4d4;
    }
    QMenuBar {
        background-color: #2d2d2d;
        color: #d4d4d4;
        border-bottom: 1px solid #3e3e3e;
    }
    QMenuBar::item:selected {
        background-color: #3e3e3e;
    }
    QMenu {
        background-color: #2d2d2d;
        color: #d4d4d4;
        border: 1px solid #3e3e3e;
    }
    QMenu::item:selected {
        background-color: #094771;
    }
    QTabWidget::pane {
        border: 1px solid #3e3e3e;
        background-color: #252526;
    }
    QTabBar::tab {
        background-color: #2d2d2d;
        color: #d4d4d4;
        padding: 8px 16px;
        border: 1px solid #3e3e3e;
        border-bottom: none;
        margin-right: 2px;
    }
    QTabBar::tab:selected {
        background-color: #252526;
        color: #ffffff;
        border-bottom: 2px solid #2980b9;
    }
    QTabBar::tab:hover {
        background-color: #3e3e3e;
    }
    QGroupBox {
        border: 1px solid #3e3e3e;
        border-radius: 4px;
        margin-top: 8px;
        padding-top: 16px;
        font-weight: bold;
        color: #d4d4d4;
    }
    QGroupBox::title {
        subcontrol-origin: margin;
        left: 10px;
        padding: 0 4px;
    }
    QTableWidget {
        background-color: #1e1e1e;
        alternate-background-color: #252526;
        gridline-color: #3e3e3e;
        color: #d4d4d4;
        border: 1px solid #3e3e3e;
        selection-background-color: #094771;
    }
    QTableWidget::item {
        padding: 4px;
    }
    QHeaderView::section {
        background-color: #2d2d2d;
        color: #d4d4d4;
        padding: 6px;
        border: 1px solid #3e3e3e;
        font-weight: bold;
    }
    QLineEdit, QSpinBox, QComboBox, QDateEdit {
        background-color: #3c3c3c;
        color: #d4d4d4;
        border: 1px solid #555;
        border-radius: 3px;
        padding: 5px;
        min-height: 22px;
    }
    QLineEdit:focus, QSpinBox:focus, QComboBox:focus, QDateEdit:focus {
        border: 1px solid #2980b9;
    }
    QComboBox::drop-down {
        border: none;
        padding-right: 8px;
    }
    QComboBox QAbstractItemView {
        background-color: #3c3c3c;
        color: #d4d4d4;
        selection-background-color: #094771;
    }
    QPushButton {
        background-color: #3c3c3c;
        color: #d4d4d4;
        border: 1px solid #555;
        border-radius: 4px;
        padding: 6px 14px;
        min-height: 22px;
    }
    QPushButton:hover {
        background-color: #4a4a4a;
    }
    QPushButton:pressed {
        background-color: #555;
    }
    QPushButton:disabled {
        background-color: #2d2d2d;
        color: #666;
    }
    QProgressBar {
        background-color: #3c3c3c;
        border: 1px solid #555;
        border-radius: 4px;
        text-align: center;
        color: #d4d4d4;
        min-height: 20px;
    }
    QProgressBar::chunk {
        background-color: #2980b9;
        border-radius: 3px;
    }
    QTextEdit {
        background-color: #1e1e1e;
        color: #969696;
        border: 1px solid #3e3e3e;
        font-family: "Menlo", "Consolas", "Courier New", monospace;
    }
    QStatusBar {
        background-color: #007acc;
        color: white;
    }
    QSplitter::handle {
        background-color: #3e3e3e;
        height: 3px;
    }
    QCheckBox {
        color: #d4d4d4;
        spacing: 6px;
    }
    QCheckBox::indicator {
        width: 16px;
        height: 16px;
        border: 1px solid #555;
        border-radius: 3px;
        background-color: #3c3c3c;
    }
    QCheckBox::indicator:checked {
        background-color: #2980b9;
        border-color: #2980b9;
    }
    QLabel {
        color: #d4d4d4;
    }
    QScrollBar:vertical {
        background-color: #1e1e1e;
        width: 12px;
        border: none;
    }
    QScrollBar::handle:vertical {
        background-color: #555;
        border-radius: 4px;
        min-height: 30px;
    }
    QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
        height: 0px;
    }
    QListWidget {
        background-color: #1e1e1e;
        color: #d4d4d4;
        border: 1px solid #3e3e3e;
        alternate-background-color: #252526;
    }
    QListWidget::item:selected {
        background-color: #094771;
    }
    QDialogButtonBox QPushButton {
        min-width: 80px;
    }
"""
